package cap.mapper;

import cap.model.BlogInfo;
import cap.model.BlogInfoWithBLOBs;

public interface BlogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    int insert(BlogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    int insertSelective(BlogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    BlogInfoWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BlogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogInfo record);
}